FROM centos:centos7.8.2003

RUN yum -y install gcc libffi-devel make openssl-devel wget which zlib zlib-devel

WORKDIR /opt/pythons
RUN wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz
RUN tar -xzf Python-3.7.5.tgz

WORKDIR /opt/pythons/Python-3.7.5/
RUN ./configure --enable-optiizations
RUN make altinstall
RUN ln -s /usr/local/bin/python3.7 /usr/bin/python3.7
RUN ln -s /usr/local/bin/pip3.7 /usr/bin/pip3.7


WORKDIR /opt/example
COPY . .

ENV POETRY_VERSION=1.0.10
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
ENV PATH="/root/.poetry/bin/:$PATH"
RUN poetry self update --preview

RUN poetry install
